### ISSUE TITLE
F-Droid badge

### ISSUE THREAD

**Issue by est31** [GunshipPenguin/open_flood#1]
The app has been made available on F-Droid: https://f-droid.org/repository/browse/?fdid=com.gunshippenguin.openflood

What about adding a badge to the readme, like this:
[![F-Droid](https://f-droid.org/wiki/images/d/d3/F-Droid-button_bigger.png)](https://f-droid.org/repository/browse/?fdid=com.gunshippenguin.openflood "Open flood on F-Droid")

Markdown source code:
```
[![F-Droid](https://f-droid.org/wiki/images/d/d3/F-Droid-button_bigger.png)](https://f-droid.org/repository/browse/?fdid=com.gunshippenguin.openflood "Open flood on F-Droid")
```

I really like the game, its cool.

**Comment by GunshipPenguin** [comment]
14595ac18dbcad8b4c514a1811940c04e6c968ca

Thanks for the positive feedback :)
