### ISSUE TITLE
Ability to play same board

### ISSUE THREAD

**Issue by tozman** [GunshipPenguin/open_flood#10]
When player loses he is forced to start a new board. Being able to play the same board may be fun when playing 2 players for example, or to test different strategies. Fun game anyway !

**Comment by GunshipPenguin** [comment]
34d4a08b0a91fa5bed6708df17a992cf7105f957

I really like this idea. Thanks for the suggestion.

**Comment by tozman** [comment]
Hey, thanks, it is great that you did it :)
