### ISSUE TITLE
colors in v1.2.0

### ISSUE THREAD

**Issue by Lvelden** [GunshipPenguin/open_flood#12]
I find the new color scheme to hard to distinguish and I'm not color blind :)

**Comment by qwertfisch** [comment]
Though I like it when colours are more bright and "happy", they also have to serve a purpose in this game. For my eyes (pretty normal ones) the new colours are too jazzy. Especially the combination of bright colours next to each other is not well chosen.

For example bright red and blue: the human eye cannot focus on both colours at once sharply, because they are at the opposite enda of the spectrum. A better way would colours with less intensive hue, like the previous colour scheme. Using blue, light blue and lilac is better than blue and red.

Maybe an option for defining own colours? I really like this game, but the colours aren't just a matter of style or aesthetics here.

**Comment by gabsoftware** [comment]
It's nice to see an update, but I think the previous colors were better, it's now harder to distinguish orange from yellow.

**Comment by GunshipPenguin** [comment]
Here is the game with saturation of board colors reduced by 20%. Old color saturation is below for comparison. Thoughts?

![newcolors](https://cloud.githubusercontent.com/assets/8054598/13727384/ab75baaa-e8a4-11e5-9708-c2d538ac6625.png)

Old color saturation for comparison.
![oldcolors](https://cloud.githubusercontent.com/assets/8054598/13727386/ad39a5a4-e8a4-11e5-82eb-ac811ca70b99.png)

**Comment by Lvelden** [comment]
Hello,
looks better could you try a higher amount of colors? 7 worked fine in the old game.

cheers,
Luuk

On Mar 13, 2016 07:54, Rhys Rustad-Elliott <notifications@github.com> wrote:

Here is the game with saturation of board colors reduced by 20%. Old color saturation is below for comparison. Thoughts?

 

Old color saturation for comparison.

**Comment by scheunengeist** [comment]
I also find the new color scheme very unpleasant to look at, especially in the context of a game such as this, where it is necessary to distinguish a lot of differently colored areas all the time and hence one has to look at the screen with great focus. I also don't see much of an improvement in the desaturated version. I don't know why the old color scheme was dropped in the first place (seemed fine to me), but perhaps it would be possible to bring it back as an option in the settings?

**Comment by zertrin** [comment]
Same problem here. I'm very slightly color blind and had no problem with the previous color set. Now I am forced to activate the numbers to play the game correctly.
The alternatives shown in this thread wouldn't help. 
Why was the previous color scheme dropped? 
Could we have it back as an option ?

**Comment by gabsoftware** [comment]
The desaturated version is better imho but still doesn't beat the original colors for clarity.

**Comment by deafboy** [comment]
Desaturated version is slightly better, but not as good as the old color scheme.

**Comment by GunshipPenguin** [comment]
The general consensus here seems to be that the desaturated colors are better but the old color scheme was better still. I like the look of the desaturated colors the best, but I understand that others would prefer the old scheme. 

In the next Open Flood release, Im going to replace the current color scheme with the desaturated scheme as well as adding an option for using the old color scheme or allowing the user to create a custom color scheme.

Give me a little bit of time, I'm going to be out of town for the next week and have a few more things slated for the next release to work on as well.

**Comment by Lvelden** [comment]
ok, thanks, good busy!

On Mar 14, 2016 09:03, Rhys Rustad-Elliott <notifications@github.com> wrote:

The general consensus here seems to be that the desaturated colors are better but the old color scheme was better still. I like the look of the desaturated colors the best, but I understand that others would prefer the old scheme. 

In the next Open Flood release, Im going to replace the current color scheme with the desaturated scheme as well as adding an option for using the old color scheme or allowing the user to create a custom color scheme.

Give me a little bit of time, I'm going to be out of town for the next week and have a few more things slated for the next release to work on as well.

**Comment by gabsoftware** [comment]
Thanks, eager to get the next release :-)

**Comment by SpiritQuaddicted** [comment]
Don't reinvent the wheel, be lazy and use the free http://colorbrewer2.org/ schemes (qualitative). They are well designed. Tick the colorblind safe box and/or printerfriendly for some good ones for this use case.

**Comment by GunshipPenguin** [comment]
ed70b50b84a83d4fd4a863df7b53f46a773f2617 and c32013dfc331d4a05cff14b46aa672227e2db1d3

**Comment by scheunengeist** [comment]
Much better, thanks for bringing back the old colors! :)

**Comment by gabsoftware** [comment]
Actually I find the desaturated color scheme more pleasant to play with. Good job :-)
