### ISSUE TITLE
High score section

### ISSUE THREAD

**Issue by gabsoftware** [GunshipPenguin/open_flood#13]
It would be nice if we could have a high score section in the game. For example I once won the game in 25 moves but nobody believes me :-)

**Comment by gabsoftware** [comment]
24 moves now! I had to take a screenshot to make my friends believing me.

**Comment by GunshipPenguin** [comment]
4370ee204b605c3bfe8cb915d8182eef98c7a8fc

I'm going to be refining the high score system a bit as well as adding the option to clear all high scores in the next release.
