### ISSUE TITLE
Board seed

### ISSUE THREAD

**Issue by gabsoftware** [GunshipPenguin/open_flood#14]
Make each board have a seed used to generate the board so that you could play a board as much as you want, and that you could eventually share with friends for competition

**Comment by gabsoftware** [comment]
Actually it is the same as issue #11

**Comment by GunshipPenguin** [comment]
I've got this feature slated for Open Flood 1.3 and know how I'm going to implement it, however it may be awhile before it comes out as I've got quite a few other commitments at the moment.

**Comment by GunshipPenguin** [comment]
487fdd4a76d98150b9edd229b70e4b17c96f2380

Got it all done in a day :)

**Comment by gabsoftware** [comment]
I'm eager to try it! :-)
