### ISSUE TITLE
320x240 resolution

### ISSUE THREAD

**Issue by asterismo** [GunshipPenguin/open_flood#15]
The board and color keys are not seen entirely please adapt it to 320x240 res, awesome game!!

**Comment by asterismo** [comment]
https://jabber.undernet.uy:5281/upload/08d572f1-5c2b-4143-ac77-34111be8af7f/a9c3674e-e326-4321-8842-8eac386e7931.jpg

**Comment by GunshipPenguin** [comment]
Currently have a working fix for this. I'd like to test it out on an actual 240x320 device though. I will make the commit on in the next few days when I have access to one and can verify that all is working properly. Here's a screenshot from an 240x320 emulator.

![smalldevice](https://cloud.githubusercontent.com/assets/8054598/13868489/895474da-ec86-11e5-9871-5e777a6dc5d1.png)
