### ISSUE TITLE
Highscore separation

### ISSUE THREAD

**Issue by smarek** [GunshipPenguin/open_flood#18]
Highscore should be separated for unique combination of grid size and number of colors, otherwise beating highscore is not possible.
Old highscore should be probably discarded with app update.

**Comment by GunshipPenguin** [comment]
Although it doesn’t explicitly say, the high score you see when you finish a board is the high score for that specific board size and number of colours. I'll add a note to clarify. 

I don't think it's necessary to discard old high scores with an app update, and doing so would be a bit inelegant as I'd probably have to store the app version along with each high score.

**Comment by GunshipPenguin** [comment]
d7f329a88cddb28413cdeefb7dda34469b5679be

**Comment by smarek** [comment]
Ok, so here's the thing. These two screenshots prove you wrong. First is from 12x12 4-color, second from 12x12 6-color. I don't see how those two are "separated" (I've cleared apps data and cache, and then played two games, producing these two screenshots)

Also comment about clearing high score, if you fix this up, then the highscore for existing users will be misleading or plain wrong, thus it should be discarded.

![screenshot_20160807-085540](https://cloud.githubusercontent.com/assets/384824/17461029/ec6946ce-5c7d-11e6-81bc-b582c77e02a1.png)
![screenshot_20160807-090151](https://cloud.githubusercontent.com/assets/384824/17461030/f233e33e-5c7d-11e6-916f-55933ee3aa69.png)

**Comment by GunshipPenguin** [comment]
Ah, I see what you mean, this is definitely a bug. 

a9fe94e940beb628cf26c2214c6e658b054a9bb9 fixes this.

Due to the way high scores are stored now, all previously stored high scores should be invalid upon an app update, and the user shouldn't see any of their old high scores.

**Comment by smarek** [comment]
Cool, thank you!
