### ISSUE TITLE
Crash and the end

### ISSUE THREAD

**Issue by jedie** [GunshipPenguin/open_flood#19]
v1.3.1 crashes after the last move.

**Comment by GunshipPenguin** [comment]
I am aware if this issue and will be releasing a fix shortly.

**Comment by GunshipPenguin** [comment]
bf145f6213cfd4c370d52f0d4070ac4dd0cd8ee7

**Comment by jedie** [comment]
I will test v1.3.2 if it's available via F-Droid.

**Comment by jedie** [comment]
Yes, its available and it works!
