### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by verdulo** [GunshipPenguin/open_flood#25]
Because Esperanto language is not selectable on most Androids, will it be possible to add to your (little) game option to change language?

**Comment by GunshipPenguin** [comment]
It feels really hackish to me to implement a language selector just because of one special case. Additionally, [The Esperanto locale seems to be available on Android 5.0 and up](https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android).

**Comment by verdulo** [comment]
Unfortunately only basic support (dates) is available on Android 5.0, you cannot select it as system language.
