### ISSUE TITLE
Similar Puzzle Game for Desktop/Browser

### ISSUE THREAD

**Issue by thenanobel** [GunshipPenguin/open_flood#28]
Hello Rhys Rustad-Elliott,

Thanks for this addictive puzzle game. I really love playing this game in my leisure time.

Anyway, I'm looking for a similar puzzle game for desktop or web. So that, I can play this game on my computer too. Can you suggest me one?

Thanks.

[Please, consider suggesting only free/libre and open source software.]

**Comment by GunshipPenguin** [comment]
Hi There,

I dug around a bit and found [this](https://www.lemoda.net/javascript/flood-it/) JavaScript flood-fill game. No license is specified, so it is therefore not FOSS, however the unobfuscated source code is provided.

There is also [this one](http://unixpapa.com/floodit/), however it too is unfortunately not FOSS.

Thanks for the positive feedback :)

**Comment by thenanobel** [comment]
Thanks for your concern. :smiley:

I had searched for a similar game, in the meantime, found [this one](https://github.com/frigidrain/flood-it/) on GitHub. Unfortunately this also doesn't have any license information. :disappointed: I have created an issue, and [asked the maintainer too add a license](https://github.com/frigidrain/flood-it/issues/2), if he had intended to make it a FLOSS.
