### ISSUE TITLE
[question] Is there always a solution?

### ISSUE THREAD

**Issue by SanskritFritz** [GunshipPenguin/open_flood#42]
In another words, are the mazes always generated in such a manner that we can be absolutely sure that there is a solution within the allowed number of steps?
Great game btw, thanks!

**Comment by GunshipPenguin** [comment]
The board is [generated totally at random](https://github.com/GunshipPenguin/open_flood/blob/master/app/src/main/java/com/gunshippenguin/openflood/Game.java#L86), it isn't guaranteed that there will always be a solution. Determining the optimal solution for a board is incredibly computationally expensive (it's NP-hard if I recall correctly), which means there's no feasible way to ensure boards are always solvable in the given number of steps.

Glad you're enjoying the game :smile:

**Comment by SanskritFritz** [comment]
Thank you, this way I won't bang my head to the wall if I can't solve a maze for the 30th time :smile:
