### ISSUE TITLE
Please tag versions in git repository 

### ISSUE THREAD

**Issue by hashar** [GunshipPenguin/open_flood#7]
It is very useful to tag releases in git for example to:
* `git bissect` an issue
* knowing which code is being used for a given bug report
* build a stable version

Looking at `app/build.gradle` history, the following commands should do the appropriate tagging:
```
git tag 1.1.0 0f61a73abc5ac928cb6d318f12eef319db718255
git tag 1.0.0 57340b42f12a31d2392a199a4f7f6ea7e6e634ce
git tag 0.1.0 4aebb4d0bc9cd7b407799e620938031e0df29aa8
git push --tags
```

Bonus points if you have a GPG key, this way you can sign them with `git tag --sign` :-D

**Comment by GunshipPenguin** [comment]
Done

Releases will be tagged with their version number from now on.

**Comment by hashar** [comment]
Thank you! Here is a tiny barnstar for being a good upstream maintainer:
```
 
          /\
         /**\
 _______/****\_______
 *.******/^^\******.*
   *.***( () )***.*
     *.**\,./**.*
      /**.**.**\
     /*.*    *.*\
    /.*        *.\
    '            `
```
