### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by TheLastProject** [GunshipPenguin/open_flood#9]
I am fortunately not colorblind myself, but I do use CyanogenMod LiveDisplay which tweaks the gamma settings to make the screen less bright at night. At these moments, I find it hard to tell screen colors apart. Some way to tell different colors apart would be nice.

Frozen Bubble solves this by drawing small characters over the bubbles, but it's hard to tell if this would work for Open Flood. Perhaps numbers or something completely different may work better.

See the image below for how Frozen Bubble does it:
![tmp_29749-screenshot_2016-02-28-00-42-22-1376721827](https://cloud.githubusercontent.com/assets/1885159/13376191/cb92c12a-ddb4-11e5-9a9f-6e655576e0c9.png)

**Comment by GunshipPenguin** [comment]
e2589e499ddb45c404e5c1de1fdc2c1c29e26517

See the attached photo to see what the new color blind mode looks like. I showed this to a color blind friend who said that it made the game playable for him.

I'm almost ready to release Open Flood 1.2, which will contain the new mode.

![colorblind](https://cloud.githubusercontent.com/assets/8054598/13588840/f10b11e4-e487-11e5-9aaf-5e3bfc8ccf47.png)
